### ISSUE TITLE
Macro commons fails to initialize when commons annotations not present in classpath

### ISSUE THREAD

**Issue by FreexD** [AVSystem/scala-commons#73]
`final val AnnotationAggregateType = getType(tq"$CommonsPkg.annotation.AnnotationAggregate")` - line 43 in MacroCommons trait

```Error:(21, 44) exception during macro expansion: 
scala.reflect.macros.TypecheckException: object annotation is not a member of package com.avsystem.commons
	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:32)
	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:26)
	at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:25)
	at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:39)
	at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:20)
	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
	at com.avsystem.commons.macros.MacroCommons.getType(MacroCommons.scala:403)
	at com.avsystem.commons.macros.MacroCommons.getType$(MacroCommons.scala:402)
	at com.avsystem.commons.macros.AbstractMacroCommons.getType(MacroCommons.scala:10)
	at com.avsystem.commons.macros.MacroCommons.$init$(MacroCommons.scala:43)
	at com.avsystem.commons.macros.AbstractMacroCommons.<init>(MacroCommons.scala:10)```

There is no dependency on commons-annotations in commons-macros.

**Comment by ghik** [comment]
No, there isn't supposed to be a dependency on `commons-annotations`, because macro implementation doesn't need it. It's needed by macro-generated code.

If there's anything to fix then it would be making `AnnotationAggregateType`  a `lazy val` so it's used only when actually needed by macro-generated code.

**Comment by ddworak** [comment]
The issue involved tests for macros, which were written in a macro project. Fixed.
